### ISSUE TITLE
translation.jsonのnoteの任意項目化

### ISSUE THREAD

**Issue by niftg** [skytomo221/ringoyaki#1]
GitLabのCIで試した限りではあるが、`translation.json`で`note`プロパティのないオブジェクトがあるとうまくビルドできない制限を緩和してほしい
（値を空文字列にすれば何も表示されない状態は実現可能だが煩雑であるため）

**Comment by skytomo221** [comment]
たしかに煩雑なので直しました
ちなみに修正箇所は[このコミット](https://github.com/skytomo221/ringoyaki/commit/efc9c106cfc8268df3d26753a19d7fa2d1e994c7)で確認できます。
